### ISSUE TITLE
Update Homepage Guage to be adaptive to the data sent at it.

### ISSUE THREAD

**Issue by sudheesh001** [uw-ictd/commgestion-web#44]
The current implementation has:
- `plotBands` which are hardcoded
    - `green` : 0 - 400
    - `yellow`: 400-600
    - `red`: 600-1000

However Once #38 is resolved, this issue needs fixes where this information can adapt to the min-max boundaries we have.

**Comment by matt9j** [comment]
We might want the administrator to input what their total backhaul available is and use that to set the gauge range?
